### ISSUE TITLE
new user: eth does not sync

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#7] opened 2017-10-02 13:17 UTC
Summary: adding a eth address to a new user does not allow to sync address data with block explorer

Steps to reproduce: register new user, login, add random eth address, no sync or error message after "add address"

Expected results: after adding the eth address it should sync the block exporer value (like btc)

Actual results: eth address without data

**Comment by d3ck-org** [comment] 2017-10-09 15:33
Tested with two new accounts: Not reproducible, seems to be fixed in the meantime.

**Closed as completed by d3ck-org** 2017-10-09 15:33 UTC
